name: Build and Obfuscate Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyinstaller pyarmor
          pip install httpx beautifulsoup4

      - name: Obfuscate Python script
        run: |
          pyarmor pack -e " --onefile" hej.py

      - name: Build executable
        run: |
          pyinstaller --onefile dist/hej.py

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: hej_executable
          path: dist/hej.exe
