name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyinstaller httpx beautifulsoup4

      - name: Compile with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name HittaEmail hej.py

      - name: Rename executable (if needed)
        run: |
          # If using a different name or location, adjust as necessary
          if (Test-Path "dist/hej.exe") { Rename-Item "dist/hej.exe" -NewName "HittaEmail.exe" }

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: hittaemail_executable
          path: dist/HittaEmail.exe
