name: Build and Obfuscate Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install nuitka
          pip install httpx beautifulsoup4

      - name: Compile with Nuitka
        run: |
          nuitka --standalone --windows-console-mode=disable --enable-plugin=tk-inter hej.py

      - name: Rename executable
        run: |
          if (Test-Path "dist/hej.exe") { Rename-Item "dist/hej.exe" -NewName "HittaEmail.exe" }

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: hittaemail_executable
          path: dist/HittaEmail.exe
